apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - port: 80           # Port inside the cluster
      targetPort: 80     # Port inside the container
      nodePort: 30080
